name: "Test"

on:
  workflow_dispatch:

env:
  file-url: "https://drive.google.com/file/d/1lKVAUmGS3y62XQmDO0GwwCSWnGXF5nQ5/view?usp=share_link"
  file-name: "test.sh"
  file-path: "$GITHUB_WORKSPACE/scripts"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wy-luke/gdrive-download
        with:
          file-url: ${{ env.file-url }}
          file-name: ${{ env.file-name }}

      - run: bash ${{ env.file-name }}
        shell: bash

      - uses: wy-luke/gdrive-download
        with:
          file-url: ${{ env.file-url }}
          file-name: ${{ env.file-name }}
          file-path: ${{ env.file-path }}

      - run: bash ${{ env.file-path }}/${{ env.file-name }}
        shell: bash
